apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-stream-sim-metrics
  namespace: kafka-stream-sim
  labels:
    app: kafka-stream-sim
    component: monitoring
spec:
  selector:
    matchLabels:
      monitoring: enabled
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scheme: http
  - port: http
    interval: 30s
    path: /actuator/prometheus
    scheme: http
  namespaceSelector:
    matchNames:
    - kafka-stream-sim

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-metrics-service
  namespace: kafka-stream-sim
  labels:
    app: kafka
    monitoring: enabled
spec:
  selector:
    app: kafka
  ports:
  - name: metrics
    port: 9308
    targetPort: 9308
    protocol: TCP
  - name: jmx
    port: 9999
    targetPort: 9999
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: producer-metrics-service
  namespace: kafka-stream-sim
  labels:
    app: producer
    monitoring: enabled
spec:
  selector:
    app: producer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: consumer-metrics-service
  namespace: kafka-stream-sim
  labels:
    app: consumer
    monitoring: enabled
spec:
  selector:
    app: consumer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: websocket-bridge-metrics-service
  namespace: kafka-stream-sim
  labels:
    app: websocket-bridge
    monitoring: enabled
spec:
  selector:
    app: websocket-bridge
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP

---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kafka-stream-sim-alerts
  namespace: kafka-stream-sim
  labels:
    app: kafka-stream-sim
    component: monitoring
spec:
  groups:
  - name: kafka-stream-sim.rules
    rules:
    - alert: KafkaStreamSimPodDown
      expr: up{job="kafka-stream-sim-metrics"} == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Kafka Stream Simulator pod is down"
        description: "Pod {{ $labels.instance }} has been down for more than 5 minutes."

    - alert: HighCPUUsage
      expr: rate(container_cpu_usage_seconds_total{namespace="kafka-stream-sim"}[5m]) * 100 > 80
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage detected"
        description: "Container {{ $labels.container }} in pod {{ $labels.pod }} is using {{ $value }}% CPU."

    - alert: HighMemoryUsage
      expr: container_memory_usage_bytes{namespace="kafka-stream-sim"} / container_spec_memory_limit_bytes * 100 > 85
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "High memory usage detected"
        description: "Container {{ $labels.container }} in pod {{ $labels.pod }} is using {{ $value }}% memory."

    - alert: KafkaConsumerLag
      expr: kafka_consumer_lag_sum > 1000
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High Kafka consumer lag"
        description: "Consumer lag is {{ $value }} messages for topic {{ $labels.topic }}."

    - alert: WebSocketConnectionsHigh
      expr: websocket_connections_active > 800
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High number of WebSocket connections"
        description: "WebSocket bridge has {{ $value }} active connections."

    - alert: PodRestartingFrequently
      expr: increase(kube_pod_container_status_restarts_total{namespace="kafka-stream-sim"}[1h]) > 3
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: "Pod restarting frequently"
        description: "Pod {{ $labels.pod }} has restarted {{ $value }} times in the last hour."

    - alert: PersistentVolumeUsageHigh
      expr: kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes * 100 > 85
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "Persistent volume usage high"
        description: "PV {{ $labels.persistentvolumeclaim }} is {{ $value }}% full."

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-kafka-stream-sim
  namespace: kafka-stream-sim
  labels:
    grafana_dashboard: "1"
data:
  kafka-stream-sim-dashboard.json: |
    {
      "dashboard": {
        "id": null,
        "title": "Kafka Stream Simulator",
        "tags": ["kafka", "streaming"],
        "style": "dark",
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "Message Throughput",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(kafka_messages_produced_total[5m])",
                "legendFormat": "Messages Produced/sec"
              },
              {
                "expr": "rate(kafka_messages_consumed_total[5m])",
                "legendFormat": "Messages Consumed/sec"
              }
            ],
            "yAxes": [
              {
                "label": "Messages/sec",
                "min": 0
              }
            ],
            "xAxis": {
              "show": true
            },
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 0,
              "y": 0
            }
          },
          {
            "id": 2,
            "title": "Consumer Lag",
            "type": "graph",
            "targets": [
              {
                "expr": "kafka_consumer_lag_sum",
                "legendFormat": "Consumer Lag"
              }
            ],
            "yAxes": [
              {
                "label": "Messages",
                "min": 0
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 12,
              "y": 0
            }
          },
          {
            "id": 3,
            "title": "WebSocket Connections",
            "type": "singlestat",
            "targets": [
              {
                "expr": "websocket_connections_active",
                "legendFormat": "Active Connections"
              }
            ],
            "gridPos": {
              "h": 4,
              "w": 6,
              "x": 0,
              "y": 8
            }
          },
          {
            "id": 4,
            "title": "Pod CPU Usage",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(container_cpu_usage_seconds_total{namespace=\"kafka-stream-sim\"}[5m]) * 100",
                "legendFormat": "{{ pod }}"
              }
            ],
            "yAxes": [
              {
                "label": "CPU %",
                "min": 0,
                "max": 100
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 0,
              "y": 12
            }
          },
          {
            "id": 5,
            "title": "Pod Memory Usage",
            "type": "graph",
            "targets": [
              {
                "expr": "container_memory_usage_bytes{namespace=\"kafka-stream-sim\"} / 1024 / 1024",
                "legendFormat": "{{ pod }}"
              }
            ],
            "yAxes": [
              {
                "label": "Memory (MB)",
                "min": 0
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 12,
              "y": 12
            }
          }
        ],
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "refresh": "30s"
      }
    }
