# Production Configuration Values for Kafka Stream Simulator
# This file contains production-ready settings for all components

# Global settings
global:
  namespace: kafka-stream-sim
  imageRegistry: docker.io
  imagePullPolicy: IfNotPresent
  storageClass: standard

# Kafka configuration
kafka:
  replicas: 3
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
  persistence:
    enabled: true
    size: "10Gi"
  jvmHeap: "-Xmx1G -Xms1G"

# Zookeeper configuration
zookeeper:
  replicas: 3
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  persistence:
    enabled: true
    size: "5Gi"
  jvmHeap: "-Xmx512M -Xms512M"

# Producer configuration
producer:
  replicas: 2
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  config:
    batchSize: 16384
    lingerMs: 5
    compressionType: "snappy"
    maxRequestSize: 1048576

# Consumer configuration
consumer:
  replicas: 2
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  config:
    maxPollRecords: 500
    sessionTimeoutMs: 30000
    heartbeatIntervalMs: 3000

# WebSocket Bridge configuration
websocketBridge:
  replicas: 2
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  config:
    maxConnections: 1000
    heartbeatInterval: 30000

# UI configuration
ui:
  replicas: 2
  resources:
    requests:
      memory: "64Mi"
      cpu: "25m"
    limits:
      memory: "128Mi"
      cpu: "100m"
  service:
    type: LoadBalancer
    port: 80
    targetPort: 80

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: kafka-stream-sim.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: kafka-stream-sim-tls
      hosts:
        - kafka-stream-sim.example.com

# Monitoring configuration
monitoring:
  enabled: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
      interval: 30s
  grafana:
    enabled: true
    dashboards:
      enabled: true

# Security configuration
security:
  networkPolicies:
    enabled: true
  podSecurityPolicy:
    enabled: true
  rbac:
    enabled: true

# Autoscaling configuration
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
